// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTz1yIsJNa2uMn2VPvLjsk7-GB85xYEUk',
    appId: '1:891130694569:web:ae53d814235ef4967f92b8',
    messagingSenderId: '891130694569',
    projectId: 'guitarist-academy-a1cd9',
    authDomain: 'guitarist-academy-a1cd9.firebaseapp.com',
    storageBucket: 'guitarist-academy-a1cd9.firebasestorage.app',
    measurementId: 'G-4XJTQD1293',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEDzXkZ4LAEpV9w5c2v-T_nUjqksRvwyQ',
    appId: '1:891130694569:android:316528121a2d32687f92b8',
    messagingSenderId: '891130694569',
    projectId: 'guitarist-academy-a1cd9',
    storageBucket: 'guitarist-academy-a1cd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFS44FmflvvWtvlw43mrw_Vr11hen5pyI',
    appId: '1:891130694569:ios:cf3289a77d1691077f92b8',
    messagingSenderId: '891130694569',
    projectId: 'guitarist-academy-a1cd9',
    storageBucket: 'guitarist-academy-a1cd9.firebasestorage.app',
    iosBundleId: 'com.example.guitaristAcademy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFS44FmflvvWtvlw43mrw_Vr11hen5pyI',
    appId: '1:891130694569:ios:cf3289a77d1691077f92b8',
    messagingSenderId: '891130694569',
    projectId: 'guitarist-academy-a1cd9',
    storageBucket: 'guitarist-academy-a1cd9.firebasestorage.app',
    iosBundleId: 'com.example.guitaristAcademy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTz1yIsJNa2uMn2VPvLjsk7-GB85xYEUk',
    appId: '1:891130694569:web:bc2ec4798325fa457f92b8',
    messagingSenderId: '891130694569',
    projectId: 'guitarist-academy-a1cd9',
    authDomain: 'guitarist-academy-a1cd9.firebaseapp.com',
    storageBucket: 'guitarist-academy-a1cd9.firebasestorage.app',
    measurementId: 'G-FDSZVTEG4B',
  );
}
